# configs/novel_writing.yaml
context:
  max_tokens: 12000
  pressure_threshold: 0.8
  relief_percentage: 0.4
  chunk_size: 3200

database:
  sqlite_path: "./data/novel_memory.db"
  qdrant_url: "http://localhost:6333"
  neo4j_url: "bolt://localhost:7687"
  neo4j_user: "neo4j"
  neo4j_password: "password"

model_name: "all-MiniLM-L6-v2"
debug: true